"""expand_customer_address_fields

Revision ID: 533015c239d4
Revises: 06d5ab8065eb
Create Date: 2026-06-24 22:07:22.161716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533015c239d4'
down_revision: Union[str, Sequence[str], None] = '06d5ab8065eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address_street', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('address_number', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('address_complement', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('address_neighborhood', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('address_state', sa.String(length=2), nullable=True))
    op.add_column('customers', sa.Column('address_zip', sa.String(length=9), nullable=True))
    op.alter_column('customers', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Observações internas',
               existing_nullable=True)
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'zip_code')
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('customers', 'notes',
               existing_type=sa.TEXT(),
               comment='Observações internas',
               existing_nullable=True)
    op.drop_column('customers', 'address_zip')
    op.drop_column('customers', 'address_state')
    op.drop_column('customers', 'address_city')
    op.drop_column('customers', 'address_neighborhood')
    op.drop_column('customers', 'address_complement')
    op.drop_column('customers', 'address_number')
    op.drop_column('customers', 'address_street')
    # ### end Alembic commands ###
